
services:
  postgres:
    container_name: postgres_new
    image: postgres
    environment:
      POSTGRES_DB: 'rabbit_mq_db'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres'
    ports:
      - '5433:5432'
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_new
    image: dpage/pgadmin4:6.10
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '5051:80'
    networks:
      - postgres
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
#  rabbitmq:
#    image: 'rabbitmq:latest'
#    environment:
#      - 'RABBITMQ_DEFAULT_PASS=secret'
#      - 'RABBITMQ_DEFAULT_USER=myuser'
#    ports:
#      - '5672'
#    networks:
#      - spring
